import { PresetTemplate, StudyTechnique } from './types';

export const STUDY_TECHNIQUES: StudyTechnique[] = [
  {
    id: 'pomodoro',
    title: 'Teknik Pomodoro Klasik',
    tagline: '25 Menit Fokus Penuh + 5 Menit Rehat Total',
    badge: 'Fokus & Anti-Burnout',
    icon: '🍅',
    description:
      'Teknik manajemen waktu legendaris yang membagi sesi belajar menjadi blok interval 25 menit konsentrasi tanpa distraksi, diselingi 5 menit istirahat teratur.',
    howItWorks: [
      'Pilih 1 topik spesifik (misal: 1 bab Biologi atau 5 rumus Fisika).',
      'Matikan notifikasi HP, pasang timer 25 menit, fokus sampai bel berbunyi.',
      'Ambil 5 menit istirahat mutlak (jalan kaki, minum air putih, jangan buka medsos).',
      'Setelah 4 putaran pomodoro, ambil istirahat panjang 15–30 menit.',
    ],
    bestFor: 'Menyicil tugas sekolah tebal, membaca materi teori panjang, riset skripsi/tugas.',
    workMinutes: 25,
    breakMinutes: 5,
    rounds: 4,
  },
  {
    id: 'feynman',
    title: 'Teknik Feynman (Active Recall)',
    tagline: '20 Menit Pahami Konsep + 10 Menit Uraikan Sederhana',
    badge: 'Penguasaan Konsep Rumit',
    icon: '🧠',
    description:
      'Metode dari peraih Nobel Richard Feynman. Kunci belajar sejati bukan menghafal, melainkan mampu menjelaskan materi sesulit apapun dengan bahasa yang sangat sederhana seolah ke anak kelas 5 SD.',
    howItWorks: [
      'Pelajari satu materi rumit selama 20 menit penuh.',
      'Tutup buku, pasang timer 10 menit.',
      'Tulis atau bicarakan materi tersebut sejelas mungkin tanpa jargon ilmiah rumit.',
      'Identifikasi di bagian mana penjelasanmu buntu atau kurang jelas, buka kembali materi di bagian itu.',
    ],
    bestFor: 'Konsep rumit matematika, fisika kuantum, reaksi kimia, hukum ekonomi, teori kedokteran.',
    workMinutes: 20,
    breakMinutes: 10,
    rounds: 3,
  },
  {
    id: 'osn_sprint',
    title: 'OSN Sprint Timeboxing',
    tagline: 'Simulasi Kecepatan Lomba (3–5 Menit per Soal)',
    badge: 'Drill Soal Kompetisi & Ujian',
    icon: '🎯',
    description:
      'Metode persiapan intensif untuk lomba seperti OSN, olimpiade, UTBK/SNBT, atau tryout. Melatih refleks berpikir cepat di bawah tekanan waktu nyata per nomor soal.',
    howItWorks: [
      'Siapkan paket 5–10 soal tipe olimpiade / lomba.',
      'Alokasikan timer 3–5 menit ketat per soal (tanpa menunda-nunda).',
      'Jika buntu pada menit ke-3, buat hipotesis tercepat dan lanjutkan ke soal berikutnya.',
      'Setelah 1 babak selesai (30–45 menit), lakukan evaluasi pola kesalahan dan trik pengerjaan cepat.',
    ],
    bestFor: 'Persiapan lomba OSN Matematika/Fisika/Informatika, tryout UTBK SNBT, ujian akhir.',
    workMinutes: 30,
    breakMinutes: 8,
    rounds: 3,
  },
];

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'sekolah',
    name: 'Jadwal Sekolah',
    icon: '🏫',
    description: 'Prioritas tugas sekolah & hari kerja (Senin–Jumat)',
    categoryType: 'schedule',
    items: [
      {
        time: '06:30',
        title: 'Siap-siap & Sarapan Pagi',
        category: 'personal',
        durationMinutes: 30,
        microStep: 'Bangun, cuci muka dengan air dingin, dan minum 1 gelas air.',
      },
      {
        time: '07:00',
        title: 'Sekolah & Sesi Belajar Utama',
        category: 'study',
        durationMinutes: 360,
        microStep: 'Buka tas sekolah dan siapkan buku mata pelajaran pertama di atas meja.',
      },
      {
        time: '13:00',
        title: 'Pulang & Istirahat Siang',
        category: 'break',
        durationMinutes: 60,
        microStep: 'Ganti seragam, taruh tas, rebahan sejenak tanpa layar HP.',
      },
      {
        time: '14:30',
        title: 'Kerjakan Tugas / PR / Bimbel',
        category: 'study',
        durationMinutes: 90,
        microStep: 'Buka buku PR-mu, baca soal nomor 1 aja dulu tanpa tekanan.',
      },
      {
        time: '16:15',
        title: 'Istirahat Sore & Santai',
        category: 'break',
        durationMinutes: 45,
        microStep: 'Jalan-jalan santai ke luar kamar, renggangkan punggung.',
      },
      {
        time: '17:30',
        title: 'Mandi & Kegiatan Bebas',
        category: 'personal',
        durationMinutes: 60,
        microStep: 'Ambil handuk dan mandi air hangat biar segar.',
      },
      {
        time: '19:00',
        title: 'Review Pelajaran Besok',
        category: 'study',
        durationMinutes: 60,
        microStep: 'Buka catatan besok, cukup baca 3 baris pertama dulu.',
      },
      {
        time: '21:30',
        title: 'Persiapan Tidur & Istirahat Total',
        category: 'personal',
        durationMinutes: 30,
        microStep: 'Colok charger HP jauh dari kasur, matikan lampu kamar.',
      },
    ],
  },
  {
    id: 'weekend',
    name: 'Jadwal Weekend',
    icon: '🏖️',
    description: 'Agenda terarah hari libur (cegah scroll HP seharian)',
    categoryType: 'schedule',
    items: [
      {
        time: '08:00',
        title: 'Bangun Santai & Sarapan Enak',
        category: 'personal',
        durationMinutes: 60,
        microStep: 'Duduk di tepi kasur 30 detik, regangkan kedua tangan ke atas.',
      },
      {
        time: '09:00',
        title: 'Olahraga Ringan / Jalan Pagi',
        category: 'personal',
        durationMinutes: 45,
        microStep: 'Pakai sandal/sepatu, jalan ke luar pintu rumah hirup udara pagi.',
      },
      {
        time: '10:00',
        title: 'Agenda Produktif / Proyek Pribadi',
        category: 'study',
        durationMinutes: 120,
        microStep: 'Buka laptop/catatan, tuliskan 1 hal kecil yang ingin dicoba.',
      },
      {
        time: '12:30',
        title: 'Makan Siang & Istirahat Siang',
        category: 'break',
        durationMinutes: 60,
        microStep: 'Makan siang santai dan nikmati waktu tanpa terburu-buru.',
      },
      {
        time: '14:30',
        title: 'Waktu Bebas / Eksplorasi Minat',
        category: 'personal',
        durationMinutes: 120,
        microStep: 'Pilih 1 kegiatan menyenangkan yang bukan sekadar scroll medsos.',
      },
      {
        time: '17:00',
        title: 'Sore Santai & Mandi Sore',
        category: 'personal',
        durationMinutes: 60,
        microStep: 'Basuh wajah dan mandi sore biar pikiran segar kembali.',
      },
      {
        time: '19:00',
        title: 'Waktu Keluarga / Sosialisasi',
        category: 'personal',
        durationMinutes: 90,
        microStep: 'Ngobrol santai bersama keluarga atau teman tanpa distraksi HP.',
      },
      {
        time: '21:30',
        title: 'Refleksi Akhir Pekan & Persiapan Tidur',
        category: 'break',
        durationMinutes: 45,
        microStep: 'Catat 1 hal baik yang terjadi minggu ini, lalu istirahat.',
      },
    ],
  },
  {
    id: 'hobby',
    name: 'Jadwal Hobby (Skill Baru)',
    icon: '🎨',
    description: 'Belajar hal baru (alat musik, merajut, dsb.) + Audio Alarm MP3 Khusus',
    categoryType: 'schedule',
    items: [
      {
        time: '15:30',
        title: 'Persiapan & Pemanasan Skill Baru',
        category: 'music',
        durationMinutes: 20,
        microStep: 'Keluarkan alat musik / perlengkapan hobimu, taruh di atas meja.',
        motivationAudioTone: 'energetic',
        hobbyAudioType: 'energetic_beat',
        hobbyAudioName: 'Beat Semangat Hobi',
      },
      {
        time: '15:50',
        title: 'Latihan Teknik Dasar / Pola Baru',
        category: 'music',
        durationMinutes: 30,
        microStep: 'Coba lakukan 1 gerakan dasar atau tangga nada pertama dengan santai.',
        motivationAudioTone: 'voice',
        hobbyAudioType: 'acoustic_melody',
        hobbyAudioName: 'Melodi Akustik Gitar',
      },
      {
        time: '16:20',
        title: 'Eksplorasi Proyek / Jamming Bebas',
        category: 'music',
        durationMinutes: 30,
        microStep: 'Mainkan atau buat pola yang paling kamu sukai tanpa takut salah.',
        motivationAudioTone: 'fanfare',
        hobbyAudioType: 'lofi_wake',
        hobbyAudioName: 'Lo-Fi Wake-Up Hobi',
      },
      {
        time: '16:50',
        title: 'Cool-down & Rapikan Peralatan',
        category: 'personal',
        durationMinutes: 15,
        microStep: 'Bersihkan dan kembalikan alat ke tempatnya, ucapkan terima kasih pada diri sendiri.',
        motivationAudioTone: 'gentle',
      },
    ],
  },
  {
    id: 'fokus_cepat',
    name: 'Fokus Cepat (Study Tools)',
    icon: '⚡',
    description: 'Tools teknik belajar cepat: Pomodoro, Feynman & OSN Sprint',
    categoryType: 'tool',
    items: [
      {
        time: '09:00',
        title: 'Sesi Fokus Intensif 1 (Sprint Belajar)',
        category: 'study',
        durationMinutes: 30,
        microStep: 'Ambil kertas coret-coret dan pulpen, tulis target 1 topik utama.',
      },
      {
        time: '09:35',
        title: 'Rest Guard Break (Istirahat Mata)',
        category: 'break',
        durationMinutes: 5,
        microStep: 'Pejamkan mata dan putar leher perlahan ke kiri dan kanan.',
      },
      {
        time: '09:40',
        title: 'Sesi Fokus Intensif 2 (Latihan Soal)',
        category: 'study',
        durationMinutes: 30,
        microStep: 'Pilih 1 soal tersulit, coba mulai uraikan bagian yang diketahui.',
      },
    ],
  },
];
